import re

pattern = re.compile(r'.*\( *(\d+)\) +([01|]+) +([0-9a-f]+) +\[ *(\d+)\]')
lines = [s.strip() for s in file('huffman-code.txt').readlines()[4:260]]
rows = [pattern.search(line).groups() for line in lines]
codes = [(int(code), int(val, 16), int(bits)) for (code, _, val, bits) in rows]

print """<?php

namespace HTTP2\\HPACK;

/* this code is generated by code. don't edit it. */

class HuffmanCodes
{
    public static $encodeHash = ["""

for (code, val, bits) in codes:
    print "        [ /* 0x%02x */ 0x%04x, %2d ]," % (code, val, bits)

print """    ];

    public static $decodeHash = ["""

bits = sorted(list(set(bits for (_, _, bits) in codes)))

for current_bits in bits:
    print "        %s => [" % current_bits

    for (code, val, bits) in codes:
        if current_bits == bits:
            print "            [ 0x%02x, 0x%x ]," % (code, val)
    print "        ],"

print """    ];
}
"""
